### ISSUE TITLE
[Feature Request] More Control

### ISSUE THREAD

**Issue by Lionirdeadman** [QingyuChai/RiceCogs#1]
- Decide which channel to use Shout in.
- Decide which channel Notify uses instead of always "main channel"

Thanks.

**Comment by QingyuChai** [comment]
sure, I'll work on that

**Comment by Lionirdeadman** [comment]
Thanks.

**Comment by QingyuChai** [comment]
@Lionirdeadman hey! For Notify, it would be very hard to change which channel it sends to because it sends to multiple servers and the other channels of each server will each have different IDs. I don't think notify will have channel selection implemented anytime in the future
