### ISSUE TITLE
Warn seems to have problems kicking user at 3 warnings.

### ISSUE THREAD

**Issue by LordCage** [QingyuChai/RiceCogs#16]
KeyError: 'kicked after 3 warnings._cases'                                      [04/04/2017 18:31] ERROR red on_command_error 364: Exception in command 'warn'  Traceback (most recent call last):                                                File "lib\discord\ext\commands\core.py", line 50, in wrapped                      ret = yield from coro(*args, **kwargs)                                        File "C:\Users\****\Desktop\****\1.0\*****\Yui\****\cogs\warn.py", line 274, in warn                                                                 reason=reason)                                                                File "C:\Users\****\Desktop\****\1.0\****\Yui\****\cogs\mod.py", line 1396, in new_case                                                             if not self.settings[server.id].get(action_type, default_settings[action_type]):                                                                            KeyError: 'kicked after 3 warnings._cases'                     

I don't know if its a bug, or its something that am doing wrong. I thought it would be the best to just hear your answer first.

**Comment by QingyuChai** [comment]
Sorry for the late reply. I have been kinda busy lately. I'll try to get it fixed.

**Comment by LordCage** [comment]
alright, best of luck to you!
