### ISSUE TITLE
Small error.

### ISSUE THREAD

**Issue by Myszkowy03** [QingyuChai/RiceCogs#18]
So, I typed `!warn (nickname)` command and I got this: `Error in command 'warn'. Check your console or logs for details.` Console: 
![bez tytulu](https://cloud.githubusercontent.com/assets/6854256/26527188/77972e58-438e-11e7-9889-c52fc6843117.png)
Is it normal or am I just stupid? I think I'm still stupid anyway.
Thanks for answer!

**Comment by QingyuChai** [comment]
Sorry, that's a bug. I'll let you know once I fix it.

**Comment by Myszkowy03** [comment]
Oh, ok. Thanks!

**Comment by Myszkowy03** [comment]
Ehh.. still nothing?

**Comment by QingyuChai** [comment]
Really sorry, dude. I just finished exams and tomorrow is the last day of school. I'll have more time to work on this.

**Comment by QingyuChai** [comment]
Sorry it took so long. Should be fixed.
