### ISSUE TITLE
[warn] [poop for every warning]

### ISSUE THREAD

**Issue by QingyuChai** [QingyuChai/RiceCogs#5]
For every warn a user has, he gets an extra 💩  in his nickname.

**Comment by QingyuChai** [comment]
or a poop nickname cog in general
💩

**Comment by Nalexa-1124** [comment]
Personally this sounds like a dumb idea IMO, but it's not my bot.

**Comment by QingyuChai** [comment]
Was just something for fun. Of course people will be allowed toggle it on and off.

**Comment by Nalexa-1124** [comment]
I hope the default is going to be off, though.
